server:
  listen: "127.0.0.1"
  authentication:
    - type: jwks
      path: auth.jwks

providers:
  - name: serial
    provider: serial
  - name: hifive-p550-mcu
    provider: hifive-p550-mcu
  - name: genio-fastboot
    provider: fastboot
    parameters:
      match:
        udev.ID_VENDOR_ID: "0e8d"
        udev.ID_MODEL_ID: "201c"
      targets:
        - mmc0
        - mmc0boot0
        - mmc0boot1
  - name: "genio-700-evk ftdi"
    provider: gpio
    parameters:
      match:
        udev.ID_USB_SERIAL_SHORT: "B001IV0D"
      lines:
        - line_number: 0
          name: "genio-700-evk-power"
        - line_number: 1
          name: "genio-700-evk-reset"
        - line_number: 2
          name: "genio-700-evk-download"

devices:
  - name: "genio-700-evk"
    consoles:
      - name: main
        parameters:
          rate: 921600
        match:
            udev.ID_SERIAL: FTDI_FT232R_USB_UART_B001IV0D
            udev.ID_USB_INTERFACE_NUM: "00"
    modes:
      - name: off
        sequence:
          - match: &genio_700_evk_power
              boardswarm.name: "genio-700-evk-reset"
            parameters:
              value: true
            stabilisation: 100ms
      - name: on
        depends: off
        sequence:
          - match: *genio_700_evk_power
            parameters:
              value: false
      - name: download
        depends: off
        sequence:
          - match: &genio_700_download
              boardswarm.name: "genio-700-evk-download"
            parameters:
              value: true
            stabilisation: 100ms
          - match: *genio_700_evk_power
            parameters:
              value: false
            stabilisation: 1s
          - match: *genio_700_download
            parameters:
              value: false
    volumes:
      - name: usb
        match:
          udev.ID_PATH: "pci-0000:00:14.0-usb-0:3.3:1.0"
      - name: fastboot
        match:
          udev.ID_PATH: "pci-0000:00:14.0-usb-0:3.3"
